name: 'Admina Custom Service Action'
author: 'Admina Team'
description: 'This is the GitHub Action to register a custom service/workspace in Admina'
inputs:
  #Common
  subcommand:
    description: 'The subcommand to run'
    required: true
    default: 'sync'
  # subcommand = sync
  source:
    description: 'The source Service Name'
    required: true
  destination:
    description: 'The destination Service Name'
    required: true
  register_zero_user_app:
    description: 'Sync or not Sync if zero users have access to the application'
    required: false
    default: 'false'
  register_disabled_app:
    description: 'Register or not register any disabled applications.'
    required: false
    default: 'false'
  target_services:
    description: 'The target services to sync'
    required: false
  ## AzureAd
  ms_client_id:
    description: 'The Azure AD client id'
    required: false
  ms_tenant_id:
    description: 'The Azure AD tenant id'
    required: false
  ms_client_secret:
    description: 'The Azure AD client secret'
    required: false
  preload_cache:
    description: 'When syncing many apps, caching in advance will make the operation faster. If you only specify a few apps in target_services, using false may be faster. This option caches all User and Group objects in advance.'
    required: false
    default: 'true'
  ## Admina
  admina_org_id:
    description: 'The Admina organization id'
    required: false
  admina_api_token:
    description: 'The Admina API token'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
