name: 'Admina Custom Service Action'
author: 'Admina Team'
description: 'This is the GitHub Action to register a custom service/workspace in Admina'
inputs:
  #Common
  subcommand:
    description: 'The subcommand to run'
    required: true
    default: 'sync'
  # subcommand = sync
  source:
    description: 'The source Service Name'
    required: true
  destination:
    description: 'The destination Service Name'
    required: true
  ## AzureAd
  ms_client_id:
    description: 'The Azure AD client id'
    required: false
  ms_tenant_id:
    description: 'The Azure AD tenant id'
    required: false
  ms_client_secret:
    description: 'The Azure AD client secret'
    required: false
  ## Admina
  admina_org_id:
    description: 'The Admina organization id'
    required: false
  admina_api_token:
    description: 'The Admina API token'
    required: false

runs:
  using: 'node16'
  main: 'dist/index.js'
